name: learning_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  logging: ^1.2.0
  path: any
  path_provider: any
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true